export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD';
export const REQUEST_CHARACTERS_PENDING = 'REQUEST_CHARACTERS_PENDING';
export const REQUEST_CHARACTERS_SUCCESS = 'REQUEST_CHARACTERS_SUCCESS';
export const REQUEST_CHARACTERS_ERROR = 'REQUEST_CHARACTERS_ERROR';
